pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public/CM-Algorithm-Specs
    - cp index.html public/index.html
    - cp CM-Algorithm-Specs/index.html public/CM-Algorithm-Specs/index.html
    - cp CM-Algorithm-Specs/CM-Algorithm-Review-Workspace.html public/CM-Algorithm-Specs/CM-Algorithm-Review-Workspace.html
    - cp CM-Algorithm-Specs/CM-Measure-Report.html public/CM-Algorithm-Specs/CM-Measure-Report.html
    - cp CM-Algorithm-Specs/*.md public/CM-Algorithm-Specs/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
