-- CM-22 field feasibility / density queries
-- Auto-generated, one query per candidate table. See the companion
-- CM-XX-Field-Feasibility-Queries.md in this directory for how to run
-- and report these back.
--
-- Dialect note: written for SQL Server / SAS PROC SQL syntax
-- (YEAR(col), COUNT(col) excludes NULLs by standard SQL semantics).
-- On Oracle, replace YEAR(<col>) with EXTRACT(YEAR FROM <col>).
-- If any column name collides with a reserved word, quote it per
-- platform ([COL] on SQL Server, "COL" on Oracle).
--
-- For very large tables, consider adding a WHERE clause to sample a
-- recent date range first (e.g. WHERE <anchor> >= '2024-01-01') to get
-- a fast initial read before running the full unfiltered query.

-- ==========================================================
-- Table: APPT_CSN_COUNTS
-- This table contains the appointment contact serial numbers (CSNs) linked to an authorization as well as the counts used for each CSN.
-- Bucket(s): Appointment / scheduling status
-- ==========================================================
-- no date/datetime-typed column found on this table; flat total only
-- (no temporal-cutover read possible from this table alone)
SELECT
    COUNT(*) AS total_rows,
    COUNT(AUTH_ID) AS AUTH_ID_filled,
    COUNT(LINE) AS LINE_filled,
    COUNT(LINKED_APPT_CSNS) AS LINKED_APPT_CSNS_filled,
    COUNT(LINKED_APPT_COUNTS) AS LINKED_APPT_COUNTS_filled,
    COUNT(USR_OVR_VST_COUNT_YN) AS USR_OVR_VST_COUNT_YN_filled
FROM APPT_CSN_COUNTS;

-- ==========================================================
-- Table: CANCELED_APPTS_EDI
-- This table contains the list of visit IDs of appointments that used to be linked to an order, but were cancelled due to the order being cancelled. This item is used by the incoming orders-to-cadence i
-- Bucket(s): Appointment / scheduling status
-- ==========================================================
-- no date/datetime-typed column found on this table; flat total only
-- (no temporal-cutover read possible from this table alone)
SELECT
    COUNT(*) AS total_rows,
    COUNT(ORDER_ID) AS ORDER_ID_filled,
    COUNT(LINE) AS LINE_filled,
    COUNT(CANCEL_APPTS_EDI) AS CANCEL_APPTS_EDI_filled,
    COUNT(CANC_APPT_PREV_STAT) AS CANC_APPT_PREV_STAT_filled
FROM CANCELED_APPTS_EDI;

-- ==========================================================
-- Table: CLARITY_SER
-- The CLARITY_SER table contains high-level information about your provider records. These records may be caregivers, resources, classes, devices, and modalities.
-- Bucket(s): Provider record (FTE / schedule — exploratory)
-- ==========================================================
-- no date/datetime-typed column found on this table; flat total only
-- (no temporal-cutover read possible from this table alone)
SELECT
    COUNT(*) AS total_rows,
    COUNT(PROV_ID_PROV_NAME) AS PROV_ID_PROV_NAME_filled,
    COUNT(PROV_NAME) AS PROV_NAME_filled,
    COUNT(EXTERNAL_NAME) AS EXTERNAL_NAME_filled
FROM CLARITY_SER;

-- ==========================================================
-- Table: ORD_AUD_APPT_INFO
-- This table contains audit information about the appointment-level info for imaging studies.
-- Bucket(s): Appointment / scheduling status
-- ==========================================================
-- no date/datetime-typed column found on this table; flat total only
-- (no temporal-cutover read possible from this table alone)
SELECT
    COUNT(*) AS total_rows,
    COUNT(ORDER_ID) AS ORDER_ID_filled,
    COUNT(LINE) AS LINE_filled,
    COUNT(APPT_STUDY_STATUES) AS APPT_STUDY_STATUES_filled,
    COUNT(APPT_STUDY_STAUES_EXT_VALS) AS APPT_STUDY_STAUES_EXT_VALS_filled
FROM ORD_AUD_APPT_INFO;

-- ==========================================================
-- Table: PAT_ENC
-- The patient encounter table contains one record for each patient encounter in your system. By default, this table does not contain Registration or PCP/Clinic Change contacts (encounter types 1 and 31)
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ID) AS PAT_ID_filled,
    COUNT(PAT_ENC_DATE_REAL) AS PAT_ENC_DATE_REAL_filled,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(PCP_PROV_ID_PROV_NAME) AS PCP_PROV_ID_PROV_NAME_filled,
    COUNT(FIN_CLASS_C_NAME) AS FIN_CLASS_C_NAME_filled,
    COUNT(VISIT_PROV_ID_PROV_NAME) AS VISIT_PROV_ID_PROV_NAME_filled,
    COUNT(VISIT_PROV_TITLE_NAME) AS VISIT_PROV_TITLE_NAME_filled,
    COUNT(DEPARTMENT_ID_EXTERNAL_NAME) AS DEPARTMENT_ID_EXTERNAL_NAME_filled,
    COUNT(LMP_DATE) AS LMP_DATE_filled,
    COUNT(ENC_CLOSED_YN) AS ENC_CLOSED_YN_filled,
    COUNT(ENC_CLOSED_USER_ID) AS ENC_CLOSED_USER_ID_filled,
    COUNT(ENC_CLOSED_USER_ID_NAME) AS ENC_CLOSED_USER_ID_NAME_filled,
    COUNT(ENC_CLOSE_DATE) AS ENC_CLOSE_DATE_filled,
    COUNT(LOS_MODIFIER1_ID) AS LOS_MODIFIER1_ID_filled,
    COUNT(LOS_MODIFIER1_ID_MODIFIER_NAME) AS LOS_MODIFIER1_ID_MODIFIER_NAME_filled,
    COUNT(LOS_MODIFIER2_ID) AS LOS_MODIFIER2_ID_filled,
    COUNT(LOS_MODIFIER2_ID_MODIFIER_NAME) AS LOS_MODIFIER2_ID_MODIFIER_NAME_filled,
    COUNT(LOS_MODIFIER3_ID) AS LOS_MODIFIER3_ID_filled,
    COUNT(LOS_MODIFIER3_ID_MODIFIER_NAME) AS LOS_MODIFIER3_ID_MODIFIER_NAME_filled,
    COUNT(LOS_MODIFIER4_ID) AS LOS_MODIFIER4_ID_filled,
    COUNT(LOS_MODIFIER4_ID_MODIFIER_NAME) AS LOS_MODIFIER4_ID_MODIFIER_NAME_filled,
    COUNT(APPT_STATUS_C_NAME) AS APPT_STATUS_C_NAME_filled,
    COUNT(APPT_CANC_USER_ID) AS APPT_CANC_USER_ID_filled,
    COUNT(APPT_CANC_USER_ID_NAME) AS APPT_CANC_USER_ID_NAME_filled,
    COUNT(CHECKIN_USER_ID) AS CHECKIN_USER_ID_filled,
    COUNT(CHECKIN_USER_ID_NAME) AS CHECKIN_USER_ID_NAME_filled,
    COUNT(HOSP_ADMSN_TIME) AS HOSP_ADMSN_TIME_filled,
    COUNT(HOSP_DISCHRG_TIME) AS HOSP_DISCHRG_TIME_filled,
    COUNT(HOSP_ADMSN_TYPE_C_NAME) AS HOSP_ADMSN_TYPE_C_NAME_filled,
    COUNT(NONCVRED_SERVICE_YN) AS NONCVRED_SERVICE_YN_filled,
    COUNT(REFERRAL_REQ_YN) AS REFERRAL_REQ_YN_filled,
    COUNT(REFERRAL_ID) AS REFERRAL_ID_filled,
    COUNT(ACCOUNT_ID) AS ACCOUNT_ID_filled,
    COUNT(COVERAGE_ID) AS COVERAGE_ID_filled,
    COUNT(CLAIM_ID) AS CLAIM_ID_filled,
    COUNT(PRIMARY_LOC_ID_LOC_NAME) AS PRIMARY_LOC_ID_LOC_NAME_filled,
    COUNT(CHARGE_SLIP_NUMBER) AS CHARGE_SLIP_NUMBER_filled,
    COUNT(COPAY_DUE) AS COPAY_DUE_filled,
    COUNT(UPDATE_DATE) AS UPDATE_DATE_filled,
    COUNT(HSP_ACCOUNT_ID) AS HSP_ACCOUNT_ID_filled,
    COUNT(ADM_FOR_SURG_YN) AS ADM_FOR_SURG_YN_filled,
    COUNT(SURGICAL_SVC_C_NAME) AS SURGICAL_SVC_C_NAME_filled,
    COUNT(INPATIENT_DATA_ID) AS INPATIENT_DATA_ID_filled,
    COUNT(IP_EPISODE_ID) AS IP_EPISODE_ID_filled,
    COUNT(EXTERNAL_VISIT_ID) AS EXTERNAL_VISIT_ID_filled,
    COUNT(CONTACT_COMMENT) AS CONTACT_COMMENT_filled,
    COUNT(OUTGOING_CALL_YN) AS OUTGOING_CALL_YN_filled,
    COUNT(DATA_ENTRY_PERSON) AS DATA_ENTRY_PERSON_filled,
    COUNT(REFERRAL_SOURCE_ID) AS REFERRAL_SOURCE_ID_filled,
    COUNT(REFERRAL_SOURCE_ID_REFERRING_PROV_NAM) AS REFERRAL_SOURCE_ID_REFERRING_PROV_NAM_filled,
    COUNT(WC_TPL_VISIT_C_NAME) AS WC_TPL_VISIT_C_NAME_filled,
    COUNT(CONSENT_TYPE_C_NAME) AS CONSENT_TYPE_C_NAME_filled,
    COUNT(BMI) AS BMI_filled,
    COUNT(BSA) AS BSA_filled,
    COUNT(AVS_PRINT_TM) AS AVS_PRINT_TM_filled,
    COUNT(AVS_FIRST_USER_ID) AS AVS_FIRST_USER_ID_filled,
    COUNT(AVS_FIRST_USER_ID_NAME) AS AVS_FIRST_USER_ID_NAME_filled,
    COUNT(ENC_MED_FRZ_RSN_C_NAME) AS ENC_MED_FRZ_RSN_C_NAME_filled,
    COUNT(EFFECTIVE_DATE_DT) AS EFFECTIVE_DATE_DT_filled,
    COUNT(DISCHARGE_DATE_DT) AS DISCHARGE_DATE_DT_filled,
    COUNT(COPAY_PD_THRU_NAME) AS COPAY_PD_THRU_NAME_filled,
    COUNT(INTERPRETER_NEED_YN) AS INTERPRETER_NEED_YN_filled,
    COUNT(VST_SPECIAL_NEEDS_C_NAME) AS VST_SPECIAL_NEEDS_C_NAME_filled,
    COUNT(BEN_ENG_SP_AMT) AS BEN_ENG_SP_AMT_filled,
    COUNT(BEN_ADJ_COPAY_AMT) AS BEN_ADJ_COPAY_AMT_filled,
    COUNT(BEN_ADJ_METHOD_C_NAME) AS BEN_ADJ_METHOD_C_NAME_filled,
    COUNT(ENC_CREATE_USER_ID) AS ENC_CREATE_USER_ID_filled,
    COUNT(ENC_CREATE_USER_ID_NAME) AS ENC_CREATE_USER_ID_NAME_filled,
    COUNT(ENC_INSTANT) AS ENC_INSTANT_filled,
    COUNT(EFFECTIVE_DATE_DTTM) AS EFFECTIVE_DATE_DTTM_filled,
    COUNT(CALCULATED_ENC_STAT_C_NAME) AS CALCULATED_ENC_STAT_C_NAME_filled
FROM PAT_ENC
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_2
-- This table supplements the PAT_ENC table. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(COPAY_COINS_FLAG) AS COPAY_COINS_FLAG_filled,
    COUNT(CAN_LET_C_NAME) AS CAN_LET_C_NAME_filled,
    COUNT(SUP_PROV_ID_PROV_NAME) AS SUP_PROV_ID_PROV_NAME_filled,
    COUNT(SUP_PROV_C_NAME) AS SUP_PROV_C_NAME_filled,
    COUNT(SUP_PROV_REV_TM) AS SUP_PROV_REV_TM_filled,
    COUNT(MEDS_REQUEST_PHR_ID) AS MEDS_REQUEST_PHR_ID_filled,
    COUNT(MEDS_REQUEST_PHR_ID_PHARMACY_NAME) AS MEDS_REQUEST_PHR_ID_PHARMACY_NAME_filled,
    COUNT(MEDS_REQUEST_OP_C_NAME) AS MEDS_REQUEST_OP_C_NAME_filled,
    COUNT(PHYS_BP) AS PHYS_BP_filled,
    COUNT(VITALS_TAKEN_TM) AS VITALS_TAKEN_TM_filled,
    COUNT(PHYS_TEMP_SRC_C_NAME) AS PHYS_TEMP_SRC_C_NAME_filled,
    COUNT(PAT_PAIN_SCORE_C_NAME) AS PAT_PAIN_SCORE_C_NAME_filled,
    COUNT(PAT_PAIN_LOC_C_NAME) AS PAT_PAIN_LOC_C_NAME_filled,
    COUNT(PAT_PAIN_EDU_YN) AS PAT_PAIN_EDU_YN_filled,
    COUNT(PAT_PAIN_CMT) AS PAT_PAIN_CMT_filled,
    COUNT(PAT_PAIN_SCALE_CAT) AS PAT_PAIN_SCALE_CAT_filled,
    COUNT(SMOKING_STATUS_C_NAME) AS SMOKING_STATUS_C_NAME_filled,
    COUNT(PHYS_SPO2) AS PHYS_SPO2_filled,
    COUNT(SYS_GEN_LOS_ID_PROC_NAME) AS SYS_GEN_LOS_ID_PROC_NAME_filled,
    COUNT(DOC_HX_SOURCE_C_NAME) AS DOC_HX_SOURCE_C_NAME_filled,
    COUNT(APPT_LET_C_NAME) AS APPT_LET_C_NAME_filled,
    COUNT(PARENT_ENC_CSN_ID) AS PARENT_ENC_CSN_ID_filled,
    COUNT(SYNC_IP_DATA_C_NAME) AS SYNC_IP_DATA_C_NAME_filled,
    COUNT(APPTMT_LET_INST) AS APPTMT_LET_INST_filled,
    COUNT(RESULT_LET_INST) AS RESULT_LET_INST_filled,
    COUNT(RESCHED_LET_INST) AS RESCHED_LET_INST_filled,
    COUNT(FOLLOW_LET_INST) AS FOLLOW_LET_INST_filled,
    COUNT(PHYS_PEAK_FLOW) AS PHYS_PEAK_FLOW_filled,
    COUNT(ENC_SPEC_C_NAME) AS ENC_SPEC_C_NAME_filled,
    COUNT(LD_STATUS_YN) AS LD_STATUS_YN_filled,
    COUNT(ADT_PAT_CLASS_C_NAME) AS ADT_PAT_CLASS_C_NAME_filled,
    COUNT(OTHER_BLOCK_ID) AS OTHER_BLOCK_ID_filled,
    COUNT(OTHER_BLOCK_TYPE_C_NAME) AS OTHER_BLOCK_TYPE_C_NAME_filled,
    COUNT(BILL_NUM) AS BILL_NUM_filled,
    COUNT(IP_DOC_CONTACT_CSN) AS IP_DOC_CONTACT_CSN_filled,
    COUNT(TEMP_PT_HIS_C_NAME) AS TEMP_PT_HIS_C_NAME_filled,
    COUNT(PRIMARY_PROCONT_ID_PROV_NAME) AS PRIMARY_PROCONT_ID_PROV_NAME_filled,
    COUNT(PRIMARY_TEAM_ID) AS PRIMARY_TEAM_ID_filled,
    COUNT(PRIMARY_TEAM_ID_RECORD_NAME) AS PRIMARY_TEAM_ID_RECORD_NAME_filled,
    COUNT(MCIR_VACCINE_CODE_C_NAME) AS MCIR_VACCINE_CODE_C_NAME_filled,
    COUNT(VISIT_POS_ID_LOC_NAME) AS VISIT_POS_ID_LOC_NAME_filled,
    COUNT(NO_INTERP_RSN_C_NAME) AS NO_INTERP_RSN_C_NAME_filled,
    COUNT(CVG_ADD_DT) AS CVG_ADD_DT_filled,
    COUNT(FARM_WORKER_C_NAME) AS FARM_WORKER_C_NAME_filled,
    COUNT(KIOSK_HH_QUEST_ID) AS KIOSK_HH_QUEST_ID_filled,
    COUNT(KIOSK_HH_QUEST_ID_RECORD_NAME) AS KIOSK_HH_QUEST_ID_RECORD_NAME_filled,
    COUNT(HSP_ACCT_ADV_DTTM) AS HSP_ACCT_ADV_DTTM_filled,
    COUNT(VISIT_VERIFIED_YN) AS VISIT_VERIFIED_YN_filled,
    COUNT(VERIF_VISIT_DT) AS VERIF_VISIT_DT_filled,
    COUNT(VERIF_DATE_INIT_DT) AS VERIF_DATE_INIT_DT_filled,
    COUNT(VERIF_USER_ID) AS VERIF_USER_ID_filled,
    COUNT(ENC_LACT_STAT_C_NAME) AS ENC_LACT_STAT_C_NAME_filled,
    COUNT(PAT_LACT_CMNT) AS PAT_LACT_CMNT_filled,
    COUNT(COSIGNER_USER_ID) AS COSIGNER_USER_ID_filled,
    COUNT(COSIGNER_USER_ID_NAME) AS COSIGNER_USER_ID_NAME_filled,
    COUNT(COSIGN_REV_INS_DTTM) AS COSIGN_REV_INS_DTTM_filled,
    COUNT(PAR_DICT_COUNTER) AS PAR_DICT_COUNTER_filled,
    COUNT(IS_LOS_UPDATE_C_NAME) AS IS_LOS_UPDATE_C_NAME_filled,
    COUNT(FORM_ID_COUNTER) AS FORM_ID_COUNTER_filled,
    COUNT(CONSNT_REV_USER_ID) AS CONSNT_REV_USER_ID_filled,
    COUNT(CONSNT_REV_USER_ID_NAME) AS CONSNT_REV_USER_ID_NAME_filled,
    COUNT(VISIT_PAYOR_ID_PAYOR_NAME) AS VISIT_PAYOR_ID_PAYOR_NAME_filled,
    COUNT(VISIT_PLAN_ID_BENEFIT_PLAN_NAME) AS VISIT_PLAN_ID_BENEFIT_PLAN_NAME_filled,
    COUNT(SOCIO_SRC_C_NAME) AS SOCIO_SRC_C_NAME_filled,
    COUNT(TEL_ENC_MSG_RGRDING) AS TEL_ENC_MSG_RGRDING_filled,
    COUNT(MSG_PRIORITY_C_NAME) AS MSG_PRIORITY_C_NAME_filled,
    COUNT(RESEARCH_ENC_FLG_C_NAME) AS RESEARCH_ENC_FLG_C_NAME_filled,
    COUNT(FAM_SPOUSE_NAME) AS FAM_SPOUSE_NAME_filled,
    COUNT(MSG_CALLER_NAME) AS MSG_CALLER_NAME_filled,
    COUNT(CONSENT_EXP_DATE) AS CONSENT_EXP_DATE_filled,
    COUNT(CV_ACC4_PAT_RESP_YN) AS CV_ACC4_PAT_RESP_YN_filled,
    COUNT(FAMILY_MEM_PREFIX_C_NAME) AS FAMILY_MEM_PREFIX_C_NAME_filled,
    COUNT(AVS_REFUSED_DTTM) AS AVS_REFUSED_DTTM_filled,
    COUNT(AVS_LAST_PRINT_DTTM) AS AVS_LAST_PRINT_DTTM_filled,
    COUNT(MED_LIST_UPDATE_DTTM) AS MED_LIST_UPDATE_DTTM_filled
FROM PAT_ENC_2
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_3
-- This table supplements the PAT_ENC and PAT_ENC_2 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(PREADMSN_TESTING_DT) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN) AS PAT_ENC_CSN_filled,
    COUNT(PAT_ENC_DATE_REAL) AS PAT_ENC_DATE_REAL_filled,
    COUNT(CHKOUT_USER_ID) AS CHKOUT_USER_ID_filled,
    COUNT(CHKOUT_USER_ID_NAME) AS CHKOUT_USER_ID_NAME_filled,
    COUNT(ENC_BILL_AREA_ID) AS ENC_BILL_AREA_ID_filled,
    COUNT(ENC_BILL_AREA_ID_BILL_AREA_NAME) AS ENC_BILL_AREA_ID_BILL_AREA_NAME_filled,
    COUNT(RX_CHG_ADMIT_FLG_C_NAME) AS RX_CHG_ADMIT_FLG_C_NAME_filled,
    COUNT(DX_UNIQUE_COUNTER) AS DX_UNIQUE_COUNTER_filled,
    COUNT(HP_DEFAULTED_YN) AS HP_DEFAULTED_YN_filled,
    COUNT(IP_CP_LAST_VAR_DTTM) AS IP_CP_LAST_VAR_DTTM_filled,
    COUNT(READY_QUT_SMOKING_C_NAME) AS READY_QUT_SMOKING_C_NAME_filled,
    COUNT(COUNSELING_GIVEN_C_NAME) AS COUNSELING_GIVEN_C_NAME_filled,
    COUNT(COMMAUTO_SENDER_ID) AS COMMAUTO_SENDER_ID_filled,
    COUNT(COMMAUTO_SENDER_ID_NAME) AS COMMAUTO_SENDER_ID_NAME_filled,
    COUNT(BENEFIT_ID) AS BENEFIT_ID_filled,
    COUNT(PREPAY_DUE_AMT) AS PREPAY_DUE_AMT_filled,
    COUNT(PREPAY_AMT_FROM_C_NAME) AS PREPAY_AMT_FROM_C_NAME_filled,
    COUNT(PREPAY_PAID_AMT) AS PREPAY_PAID_AMT_filled,
    COUNT(PREADMSN_TESTING_DT) AS PREADMSN_TESTING_DT_filled,
    COUNT(SMK_CESS_USER_ID) AS SMK_CESS_USER_ID_filled,
    COUNT(SMK_CESS_USER_ID_NAME) AS SMK_CESS_USER_ID_NAME_filled,
    COUNT(SMK_CESS_DTTM) AS SMK_CESS_DTTM_filled,
    COUNT(DO_NOT_BILL_INS_YN) AS DO_NOT_BILL_INS_YN_filled,
    COUNT(SELF_PAY_VISIT_YN) AS SELF_PAY_VISIT_YN_filled,
    COUNT(REFERRAL_TYPE_C_NAME) AS REFERRAL_TYPE_C_NAME_filled,
    COUNT(SCHOOL) AS SCHOOL_filled,
    COUNT(COPAY_NUM_UNITS) AS COPAY_NUM_UNITS_filled,
    COUNT(COPAY_AMT_PER_UNIT) AS COPAY_AMT_PER_UNIT_filled,
    COUNT(COPAY_LASTCALC_DT) AS COPAY_LASTCALC_DT_filled,
    COUNT(COPAY_OVERRIDDEN_YN) AS COPAY_OVERRIDDEN_YN_filled,
    COUNT(OB_TOTAL_WT_GAIN) AS OB_TOTAL_WT_GAIN_filled,
    COUNT(MEDICAID_GROUP_NAME) AS MEDICAID_GROUP_NAME_filled,
    COUNT(STUDENT_STATUS_C_NAME) AS STUDENT_STATUS_C_NAME_filled,
    COUNT(MEDICAID_GROUP_ID) AS MEDICAID_GROUP_ID_filled,
    COUNT(EXTERNAL_REF_ID) AS EXTERNAL_REF_ID_filled,
    COUNT(OUTCOME_C_NAME) AS OUTCOME_C_NAME_filled,
    COUNT(HSPC_NO_ADM_C_NAME) AS HSPC_NO_ADM_C_NAME_filled
FROM PAT_ENC_3
GROUP BY YEAR(PREADMSN_TESTING_DT)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_4
-- This table supplements the PAT_ENC, PAT_ENC_2, and PAT_ENC_3 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(LB_ENC_START_DT) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(FAMILY_SIZE) AS FAMILY_SIZE_filled,
    COUNT(VISIT_NUMBER) AS VISIT_NUMBER_filled,
    COUNT(PAT_CNCT_IND_C_NAME) AS PAT_CNCT_IND_C_NAME_filled,
    COUNT(DENTAL_STUDENT_ID_PROV_NAME) AS DENTAL_STUDENT_ID_PROV_NAME_filled,
    COUNT(LOC_VISIT_ID_LOC_NAME) AS LOC_VISIT_ID_LOC_NAME_filled,
    COUNT(COPAY_NOT_COVERED_C_NAME) AS COPAY_NOT_COVERED_C_NAME_filled,
    COUNT(COPAY_COLL_FLAG_YN) AS COPAY_COLL_FLAG_YN_filled,
    COUNT(COPAY_COLL_PERSON) AS COPAY_COLL_PERSON_filled,
    COUNT(COPAY_WAIVE_RSN_C_NAME) AS COPAY_WAIVE_RSN_C_NAME_filled,
    COUNT(COPAY_MIN_VALUE) AS COPAY_MIN_VALUE_filled,
    COUNT(COPAY_RECEIPT_NUM) AS COPAY_RECEIPT_NUM_filled,
    COUNT(BEN_ADJ_COINS_AMT) AS BEN_ADJ_COINS_AMT_filled,
    COUNT(BEN_ADJ_DEDUCT_AMT) AS BEN_ADJ_DEDUCT_AMT_filled,
    COUNT(PAT_HOMELESS_YN) AS PAT_HOMELESS_YN_filled,
    COUNT(PAT_HOMELESS_TYP_C_NAME) AS PAT_HOMELESS_TYP_C_NAME_filled,
    COUNT(PERCENTAGE_OF_FPL) AS PERCENTAGE_OF_FPL_filled,
    COUNT(MSG_RECEIVED_DTTM) AS MSG_RECEIVED_DTTM_filled,
    COUNT(TOBACCO_USE_VRFY_YN) AS TOBACCO_USE_VRFY_YN_filled,
    COUNT(CR_TX_TYPE_C_NAME) AS CR_TX_TYPE_C_NAME_filled,
    COUNT(ORIG_ENC_CSN) AS ORIG_ENC_CSN_filled,
    COUNT(PHYS_BP_COMMENTS) AS PHYS_BP_COMMENTS_filled,
    COUNT(PHYS_TEMP_COMMENTS) AS PHYS_TEMP_COMMENTS_filled,
    COUNT(PHYS_TEMPSRC_COMNTS) AS PHYS_TEMPSRC_COMNTS_filled,
    COUNT(PHYS_PULSE_COMMENTS) AS PHYS_PULSE_COMMENTS_filled,
    COUNT(PHYS_WEIGHT_COMNTS) AS PHYS_WEIGHT_COMNTS_filled,
    COUNT(PHYS_HEIGHT_COMNTS) AS PHYS_HEIGHT_COMNTS_filled,
    COUNT(PHYS_RESP_COMMENTS) AS PHYS_RESP_COMMENTS_filled,
    COUNT(PHYS_SPO2_COMMENTS) AS PHYS_SPO2_COMMENTS_filled,
    COUNT(PHYS_PF_COMMENTS) AS PHYS_PF_COMMENTS_filled,
    COUNT(INTERPRT_ASGN_CMT) AS INTERPRT_ASGN_CMT_filled,
    COUNT(PAT_HOUSING_STAT_C_NAME) AS PAT_HOUSING_STAT_C_NAME_filled,
    COUNT(BCRA_AGE) AS BCRA_AGE_filled,
    COUNT(BCRA_MENARCHE_AGE_C_NAME) AS BCRA_MENARCHE_AGE_C_NAME_filled,
    COUNT(BCRA_FST_LIVBIRTH_C_NAME) AS BCRA_FST_LIVBIRTH_C_NAME_filled,
    COUNT(BCRA_FST_DEG_REL_C_NAME) AS BCRA_FST_DEG_REL_C_NAME_filled,
    COUNT(BCRA_NUM_BIOPSY_C_NAME) AS BCRA_NUM_BIOPSY_C_NAME_filled,
    COUNT(BCRA_ATYP_HYPLSA_C_NAME) AS BCRA_ATYP_HYPLSA_C_NAME_filled,
    COUNT(BCRA_RACE_C_NAME) AS BCRA_RACE_C_NAME_filled,
    COUNT(LB_ENC_START_DT) AS LB_ENC_START_DT_filled,
    COUNT(LB_ENC_END_DT) AS LB_ENC_END_DT_filled,
    COUNT(WAITING_LIST_ID) AS WAITING_LIST_ID_filled,
    COUNT(SUBMITTER_ID) AS SUBMITTER_ID_filled,
    COUNT(SUBMITTER_ID_RECORD_NAME) AS SUBMITTER_ID_RECORD_NAME_filled,
    COUNT(BILL_TO_SUBMITTER_C_NAME) AS BILL_TO_SUBMITTER_C_NAME_filled,
    COUNT(SUBMITTER_ACCT_ID) AS SUBMITTER_ACCT_ID_filled,
    COUNT(LB_BLNG_ENC_SRVC_DT) AS LB_BLNG_ENC_SRVC_DT_filled,
    COUNT(ECHKIN_STATUS_C_NAME) AS ECHKIN_STATUS_C_NAME_filled,
    COUNT(PB_VISIT_HAR_ID) AS PB_VISIT_HAR_ID_filled,
    COUNT(TECHNICAL_REFERRAL_ID) AS TECHNICAL_REFERRAL_ID_filled,
    COUNT(CR_CLIENT_REF_IDNT) AS CR_CLIENT_REF_IDNT_filled,
    COUNT(CR_BENEFIT_REF_IDNT) AS CR_BENEFIT_REF_IDNT_filled,
    COUNT(CR_MESSAGE_ENGLISH) AS CR_MESSAGE_ENGLISH_filled,
    COUNT(CR_MESSAGE_SPANISH) AS CR_MESSAGE_SPANISH_filled,
    COUNT(CR_QUERY_SENT_UTC_DTTM) AS CR_QUERY_SENT_UTC_DTTM_filled,
    COUNT(CR_RESP_RECVD_UTC_DTTM) AS CR_RESP_RECVD_UTC_DTTM_filled,
    COUNT(CR_QUERY_ERROR) AS CR_QUERY_ERROR_filled,
    COUNT(COPAY_REDUCTION_AMT) AS COPAY_REDUCTION_AMT_filled
FROM PAT_ENC_4
GROUP BY YEAR(LB_ENC_START_DT)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_5
-- This table supplements the PAT_ENC, PAT_ENC_2, PAT_ENC_3, and PAT_ENC_4 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(PUBLIC_HOUSING_YN) AS PUBLIC_HOUSING_YN_filled,
    COUNT(PVT_HOSP_ENC_C_NAME) AS PVT_HOSP_ENC_C_NAME_filled,
    COUNT(LINK_INS_TYPE_C_NAME) AS LINK_INS_TYPE_C_NAME_filled,
    COUNT(PAT_VER_HCA_C_NAME) AS PAT_VER_HCA_C_NAME_filled,
    COUNT(EXT_GRP_IDNT) AS EXT_GRP_IDNT_filled,
    COUNT(EXT_GRP_SRC_C_NAME) AS EXT_GRP_SRC_C_NAME_filled,
    COUNT(PREPAY_SET_BY_USER_YN) AS PREPAY_SET_BY_USER_YN_filled,
    COUNT(PREPAY_UPDATE_USER_ID) AS PREPAY_UPDATE_USER_ID_filled,
    COUNT(PREPAY_UPDATE_USER_ID_NAME) AS PREPAY_UPDATE_USER_ID_NAME_filled,
    COUNT(PREPAY_UPDATE_INST_DTTM) AS PREPAY_UPDATE_INST_DTTM_filled,
    COUNT(PREPAY_CALC_SCENARIO) AS PREPAY_CALC_SCENARIO_filled,
    COUNT(AUTHCERT_ID) AS AUTHCERT_ID_filled,
    COUNT(ED_REF_CALLBAK_YN) AS ED_REF_CALLBAK_YN_filled,
    COUNT(ED_REF_CALLBAK_P_ID_PROV_NAME) AS ED_REF_CALLBAK_P_ID_PROV_NAME_filled,
    COUNT(ED_REF_CALLBAK_C_ID_LOC_NAME) AS ED_REF_CALLBAK_C_ID_LOC_NAME_filled,
    COUNT(ED_REF_CALLBAK_NUM) AS ED_REF_CALLBAK_NUM_filled,
    COUNT(IS_ON_DEMAND_VV_YN) AS IS_ON_DEMAND_VV_YN_filled,
    COUNT(ATTR_DEPARTMENT_ID_EXTERNAL_NAME) AS ATTR_DEPARTMENT_ID_EXTERNAL_NAME_filled,
    COUNT(PAT_DTREE_ANSWER_ID) AS PAT_DTREE_ANSWER_ID_filled,
    COUNT(PREPAY_DISCNT_AMT) AS PREPAY_DISCNT_AMT_filled,
    COUNT(PREPAY_DISCNT_PCT) AS PREPAY_DISCNT_PCT_filled,
    COUNT(PREPAY_PROPOSED_DISCNT_AMT) AS PREPAY_PROPOSED_DISCNT_AMT_filled,
    COUNT(PREPAY_DISCNT_CALC_RULE_ID) AS PREPAY_DISCNT_CALC_RULE_ID_filled,
    COUNT(PREPAY_DISCNT_CALC_RULE_ID_RULE_NAME) AS PREPAY_DISCNT_CALC_RULE_ID_RULE_NAME_filled,
    COUNT(PREPAY_DISCNT_CALC_PCT) AS PREPAY_DISCNT_CALC_PCT_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_AMT) AS PREPAY_DISCNT_OVRIDE_AMT_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_PCT) AS PREPAY_DISCNT_OVRIDE_PCT_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_USER_ID) AS PREPAY_DISCNT_OVRIDE_USER_ID_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_USER_ID_NAME) AS PREPAY_DISCNT_OVRIDE_USER_ID_NAME_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_CMT) AS PREPAY_DISCNT_OVRIDE_CMT_filled,
    COUNT(PREPAY_DISCNT_OVRIDE_DTTM) AS PREPAY_DISCNT_OVRIDE_DTTM_filled,
    COUNT(EVISIT_STATUS_C_NAME) AS EVISIT_STATUS_C_NAME_filled
FROM PAT_ENC_5
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_6
-- This table supplements the PAT_ENC, PAT_ENC_2, PAT_ENC_3, PAT_ENC_4, and PAT_ENC_5 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(PAT_ENC_DATE_REAL) AS PAT_ENC_DATE_REAL_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(LINKED_ENC_CSN) AS LINKED_ENC_CSN_filled,
    COUNT(LMP_PRECISION_C_NAME) AS LMP_PRECISION_C_NAME_filled,
    COUNT(PLANNED_BILL_AREA_ID) AS PLANNED_BILL_AREA_ID_filled,
    COUNT(PLANNED_BILL_AREA_ID_BILL_AREA_NAME) AS PLANNED_BILL_AREA_ID_BILL_AREA_NAME_filled,
    COUNT(BCRA_BRCA_GENE_MUT_C_NAME) AS BCRA_BRCA_GENE_MUT_C_NAME_filled,
    COUNT(SVC_TARGET_EFFORT_YN) AS SVC_TARGET_EFFORT_YN_filled,
    COUNT(OUTPAT_VISIT_GRP_C_NAME) AS OUTPAT_VISIT_GRP_C_NAME_filled,
    COUNT(PSYCH_ARRIVAL_C_NAME) AS PSYCH_ARRIVAL_C_NAME_filled,
    COUNT(PLAN_RECUR_TREAT_YN) AS PLAN_RECUR_TREAT_YN_filled,
    COUNT(HUS_VISIT_TYPE_C_NAME) AS HUS_VISIT_TYPE_C_NAME_filled,
    COUNT(SOCIAL_SRVC_AREA_C_NAME) AS SOCIAL_SRVC_AREA_C_NAME_filled,
    COUNT(EXT_LTC_PAT_YN) AS EXT_LTC_PAT_YN_filled,
    COUNT(VETERAN_ENC_MED_CVG_C_NAME) AS VETERAN_ENC_MED_CVG_C_NAME_filled,
    COUNT(VETERAN_BILLING_CODE_C_NAME) AS VETERAN_BILLING_CODE_C_NAME_filled,
    COUNT(ED_REF_CALLBAK_D_ID_EXTERNAL_NAME) AS ED_REF_CALLBAK_D_ID_EXTERNAL_NAME_filled,
    COUNT(RFV_USED_TO_SCHED_C_NAME) AS RFV_USED_TO_SCHED_C_NAME_filled,
    COUNT(BMI_PERCENTILE) AS BMI_PERCENTILE_filled,
    COUNT(CREATION_ORD_ID) AS CREATION_ORD_ID_filled,
    COUNT(EXT_TX_STATUS_C_NAME) AS EXT_TX_STATUS_C_NAME_filled,
    COUNT(EXT_TX_STATUS_CMT) AS EXT_TX_STATUS_CMT_filled,
    COUNT(EXT_ACCM_STATUS_C_NAME) AS EXT_ACCM_STATUS_C_NAME_filled,
    COUNT(EXT_ACCM_STATUS_CMT) AS EXT_ACCM_STATUS_CMT_filled,
    COUNT(SG_AT_RISK_IND_C_NAME) AS SG_AT_RISK_IND_C_NAME_filled,
    COUNT(SG_FC_STATUS_C_NAME) AS SG_FC_STATUS_C_NAME_filled,
    COUNT(ELIG_PLAN_SELECT_YN) AS ELIG_PLAN_SELECT_YN_filled,
    COUNT(SG_MOH_URGENCY_C_NAME) AS SG_MOH_URGENCY_C_NAME_filled,
    COUNT(SG_NAMED_REFERRAL_YN) AS SG_NAMED_REFERRAL_YN_filled,
    COUNT(SG_PAT_REQUEST_YN) AS SG_PAT_REQUEST_YN_filled,
    COUNT(SG_TREATMENT_PROG_C_NAME) AS SG_TREATMENT_PROG_C_NAME_filled,
    COUNT(SG_APPT_RATIONALE_C_NAME) AS SG_APPT_RATIONALE_C_NAME_filled,
    COUNT(EVISIT_RFV_C_NAME) AS EVISIT_RFV_C_NAME_filled,
    COUNT(EVISIT_YN) AS EVISIT_YN_filled,
    COUNT(EVISIT_TLH_ALLOWED_SUBLOC_C_NAME) AS EVISIT_TLH_ALLOWED_SUBLOC_C_NAME_filled,
    COUNT(EVISIT_TLH_ALLOWED_LOC_C_NAME) AS EVISIT_TLH_ALLOWED_LOC_C_NAME_filled,
    COUNT(APPT_AUTH_STATUS_C_NAME) AS APPT_AUTH_STATUS_C_NAME_filled,
    COUNT(EVISIT_NEW_STATUS_C_NAME) AS EVISIT_NEW_STATUS_C_NAME_filled,
    COUNT(LAB_RESP_USER_ID) AS LAB_RESP_USER_ID_filled,
    COUNT(LAB_RESP_USER_ID_NAME) AS LAB_RESP_USER_ID_NAME_filled,
    COUNT(EXT_MEDS_UPD_INST_UTC_DTTM) AS EXT_MEDS_UPD_INST_UTC_DTTM_filled,
    COUNT(INTF_PRIMARY_PAT_ENC_CSN_ID) AS INTF_PRIMARY_PAT_ENC_CSN_ID_filled,
    COUNT(OVERRIDE_BCRA_NUM_BIOPSY_C_NAME) AS OVERRIDE_BCRA_NUM_BIOPSY_C_NAME_filled,
    COUNT(OVERRIDE_BCRA_RACE_C_NAME) AS OVERRIDE_BCRA_RACE_C_NAME_filled,
    COUNT(OVERRIDE_GAIL_FACTOR_USER_ID) AS OVERRIDE_GAIL_FACTOR_USER_ID_filled,
    COUNT(OVERRIDE_GAIL_FACTOR_USER_ID_NAME) AS OVERRIDE_GAIL_FACTOR_USER_ID_NAME_filled,
    COUNT(OVERRIDE_GAIL_FACTOR_DTTM) AS OVERRIDE_GAIL_FACTOR_DTTM_filled,
    COUNT(VETERAN_COVERAGE_ENC_YN) AS VETERAN_COVERAGE_ENC_YN_filled,
    COUNT(ADJUD_TO_PHARMACY_COVERAGE_YN) AS ADJUD_TO_PHARMACY_COVERAGE_YN_filled,
    COUNT(TLH_APRV_SUBLOC_C_NAME) AS TLH_APRV_SUBLOC_C_NAME_filled,
    COUNT(TLH_APRV_LOC_C_NAME) AS TLH_APRV_LOC_C_NAME_filled,
    COUNT(ENC_CLOSE_UTC_DTTM) AS ENC_CLOSE_UTC_DTTM_filled,
    COUNT(SPLIT_FILING_ORDER_YN) AS SPLIT_FILING_ORDER_YN_filled
FROM PAT_ENC_6
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_7
-- This table supplements the PAT_ENC, PAT_ENC_2, PAT_ENC_3, PAT_ENC_4, PAT_ENC_5, and PAT_ENC_6 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(PAT_ENC_DATE_REAL) AS PAT_ENC_DATE_REAL_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(NOTIFY_REP_ADMSN_C_NAME) AS NOTIFY_REP_ADMSN_C_NAME_filled,
    COUNT(REP_NOTIFIED_C_NAME) AS REP_NOTIFIED_C_NAME_filled,
    COUNT(NOTIFY_REP_COMMENTS) AS NOTIFY_REP_COMMENTS_filled,
    COUNT(NOTIFY_PCP_ADMSN_C_NAME) AS NOTIFY_PCP_ADMSN_C_NAME_filled,
    COUNT(PCP_NOTIFIED_C_NAME) AS PCP_NOTIFIED_C_NAME_filled,
    COUNT(NOTIFY_PCP_COMMENTS) AS NOTIFY_PCP_COMMENTS_filled,
    COUNT(ROC_PLANNING_PAT_ENC_CSN_ID) AS ROC_PLANNING_PAT_ENC_CSN_ID_filled,
    COUNT(NUM_PREV_EPSD_C_NAME) AS NUM_PREV_EPSD_C_NAME_filled,
    COUNT(SPEC_ORD_RSLT_NOT_AUTO_RLS_YN) AS SPEC_ORD_RSLT_NOT_AUTO_RLS_YN_filled,
    COUNT(RECENTLY_AT_SCHOOL_C_NAME) AS RECENTLY_AT_SCHOOL_C_NAME_filled,
    COUNT(LMP_COMMENT) AS LMP_COMMENT_filled,
    COUNT(CONTACT_NUM) AS CONTACT_NUM_filled,
    COUNT(ABN_REQUIRED_YN) AS ABN_REQUIRED_YN_filled,
    COUNT(IS_ABN_SIGNED_C_NAME) AS IS_ABN_SIGNED_C_NAME_filled,
    COUNT(MSP_IS_MEDICARE_HMO_C_NAME) AS MSP_IS_MEDICARE_HMO_C_NAME_filled,
    COUNT(REG_COMMENTS_DATE) AS REG_COMMENTS_DATE_filled,
    COUNT(AUTO_MSG_DISABLED_YN) AS AUTO_MSG_DISABLED_YN_filled,
    COUNT(DONT_AUTO_LINK_YN) AS DONT_AUTO_LINK_YN_filled,
    COUNT(RSN_FOR_NO_INC_MSG_C_NAME) AS RSN_FOR_NO_INC_MSG_C_NAME_filled,
    COUNT(HAS_HORMONE_DATA_YN) AS HAS_HORMONE_DATA_YN_filled,
    COUNT(MEDS_REQUEST_LWS_ID_WORKSTATION_NAME) AS MEDS_REQUEST_LWS_ID_WORKSTATION_NAME_filled,
    COUNT(EVISIT_SUBMITTED_DTTM) AS EVISIT_SUBMITTED_DTTM_filled,
    COUNT(EVISIT_TURNAROUND_IN_MINUTES) AS EVISIT_TURNAROUND_IN_MINUTES_filled,
    COUNT(PREGNANCY_INTENTION_C_NAME) AS PREGNANCY_INTENTION_C_NAME_filled,
    COUNT(PREGNANCY_COUNSELED_YN) AS PREGNANCY_COUNSELED_YN_filled,
    COUNT(BIRTH_CONTROL_COUNSELED_YN) AS BIRTH_CONTROL_COUNSELED_YN_filled,
    COUNT(RSN_NO_BCM_COUNSELING_C_NAME) AS RSN_NO_BCM_COUNSELING_C_NAME_filled,
    COUNT(INTAKE_RSN_NO_CONTRACEPTIVE_C_NAME) AS INTAKE_RSN_NO_CONTRACEPTIVE_C_NAME_filled,
    COUNT(CONTRACEPTIVE_DELIVERY_C_NAME) AS CONTRACEPTIVE_DELIVERY_C_NAME_filled,
    COUNT(EXIT_RSN_NO_CONTRACEPTIVE_C_NAME) AS EXIT_RSN_NO_CONTRACEPTIVE_C_NAME_filled,
    COUNT(IS_VAP_DECLINED_YN) AS IS_VAP_DECLINED_YN_filled,
    COUNT(EPISODE_UPDATE_EFF_DATE) AS EPISODE_UPDATE_EFF_DATE_filled,
    COUNT(EPISODE_UPD_CREAT_RSN_C_NAME) AS EPISODE_UPD_CREAT_RSN_C_NAME_filled,
    COUNT(VISIT_MSG_DECLINE_YN) AS VISIT_MSG_DECLINE_YN_filled,
    COUNT(BILL_FOR_DENIAL_YN) AS BILL_FOR_DENIAL_YN_filled
FROM PAT_ENC_7
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_8
-- This table supplements the PAT_ENC, PAT_ENC_2, PAT_ENC_3, PAT_ENC_4, PAT_ENC_5, PAT_ENC_6, and PAT_ENC_7 tables. It contains additional information related to patient encounters or appointments.
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(PAT_ID) AS PAT_ID_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(CM_CT_OWNER_ID) AS CM_CT_OWNER_ID_filled,
    COUNT(EST_PREPAY_CALC_PP_PROPOSED_YN) AS EST_PREPAY_CALC_PP_PROPOSED_YN_filled,
    COUNT(EST_PREPAY_CALC_ELIG_C_NAME) AS EST_PREPAY_CALC_ELIG_C_NAME_filled,
    COUNT(PMT_PLAN_AGRMT_SCHED_PMT_ID) AS PMT_PLAN_AGRMT_SCHED_PMT_ID_filled,
    COUNT(RSLT_FOL_UP_CREAT_SRC_C_NAME) AS RSLT_FOL_UP_CREAT_SRC_C_NAME_filled,
    COUNT(BILL_DECIS_FIN_ASST_TRACKER_ID) AS BILL_DECIS_FIN_ASST_TRACKER_ID_filled,
    COUNT(NO_FOLLOW_UP_YN) AS NO_FOLLOW_UP_YN_filled,
    COUNT(MCAID_INCARCERATION_BILL_CODE) AS MCAID_INCARCERATION_BILL_CODE_filled,
    COUNT(MCAID_INCAR_BILL_START_DATE) AS MCAID_INCAR_BILL_START_DATE_filled,
    COUNT(MEDICARE_CHANGE_C_NAME) AS MEDICARE_CHANGE_C_NAME_filled,
    COUNT(MSP_RTE_VERI_STAT_C_NAME) AS MSP_RTE_VERI_STAT_C_NAME_filled,
    COUNT(MSP_COMP_REALTIME_TX_CSN_ID) AS MSP_COMP_REALTIME_TX_CSN_ID_filled,
    COUNT(MSP_RTE_COMP_PAT_ENC_CSN_ID) AS MSP_RTE_COMP_PAT_ENC_CSN_ID_filled,
    COUNT(TAKING_PULL_REJECTED_YN) AS TAKING_PULL_REJECTED_YN_filled,
    COUNT(HOSP_SERV_C_NAME) AS HOSP_SERV_C_NAME_filled,
    COUNT(LEVEL_OF_CARE_C_NAME) AS LEVEL_OF_CARE_C_NAME_filled,
    COUNT(ACCOMMODATION_C_NAME) AS ACCOMMODATION_C_NAME_filled,
    COUNT(ACCOM_REASON_C_NAME) AS ACCOM_REASON_C_NAME_filled,
    COUNT(APPT_NEEDS_BED_C_NAME) AS APPT_NEEDS_BED_C_NAME_filled,
    COUNT(APPT_BED_PREDEPT_ID_EXTERNAL_NAME) AS APPT_BED_PREDEPT_ID_EXTERNAL_NAME_filled,
    COUNT(APPT_BED_HOSP_SERV_C_NAME) AS APPT_BED_HOSP_SERV_C_NAME_filled,
    COUNT(APPT_BED_POST_LEVEL_OF_CARE_C_NAME) AS APPT_BED_POST_LEVEL_OF_CARE_C_NAME_filled,
    COUNT(APPT_BED_CMT_S) AS APPT_BED_CMT_S_filled,
    COUNT(SEPARATED_GROUP_YN) AS SEPARATED_GROUP_YN_filled
FROM PAT_ENC_8
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_APPT
-- The PAT_ENC_APPT table contains basic information about the appointment records in your system. Since one patient encounter can be an appointment with multiple providers and resources (joint appointme
-- Bucket(s): Appointment / scheduling status
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(LINE) AS LINE_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(DEPARTMENT_ID_EXTERNAL_NAME) AS DEPARTMENT_ID_EXTERNAL_NAME_filled,
    COUNT(PROV_START_TIME) AS PROV_START_TIME_filled,
    COUNT(APPT_PROV_PRIMARY_SPECIALTY_C_NAME) AS APPT_PROV_PRIMARY_SPECIALTY_C_NAME_filled
FROM PAT_ENC_APPT
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_HSP
-- This table is the primary table for hospital encounter information. A hospital encounter is a contact in the patient record created through an ADT workflow such as preadmission, admission, ED Arrival,
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(EXP_DISCHARGE_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(ADT_PAT_CLASS_C_NAME) AS ADT_PAT_CLASS_C_NAME_filled,
    COUNT(ADT_PATIENT_STAT_C_NAME) AS ADT_PATIENT_STAT_C_NAME_filled,
    COUNT(LEVEL_OF_CARE_C_NAME) AS LEVEL_OF_CARE_C_NAME_filled,
    COUNT(PENDING_DISCH_TIME) AS PENDING_DISCH_TIME_filled,
    COUNT(DISCH_CODE_C_NAME) AS DISCH_CODE_C_NAME_filled,
    COUNT(ADT_ATHCRT_STAT_C_NAME) AS ADT_ATHCRT_STAT_C_NAME_filled,
    COUNT(PREADM_UNDO_RSN_C_NAME) AS PREADM_UNDO_RSN_C_NAME_filled,
    COUNT(EXP_ADMISSION_TIME) AS EXP_ADMISSION_TIME_filled,
    COUNT(EXP_LEN_OF_STAY) AS EXP_LEN_OF_STAY_filled,
    COUNT(EXP_DISCHARGE_DATE) AS EXP_DISCHARGE_DATE_filled,
    COUNT(ADMIT_CATEGORY_C_NAME) AS ADMIT_CATEGORY_C_NAME_filled,
    COUNT(ADMIT_SOURCE_C_NAME) AS ADMIT_SOURCE_C_NAME_filled,
    COUNT(TYPE_OF_ROOM_C_NAME) AS TYPE_OF_ROOM_C_NAME_filled,
    COUNT(TYPE_OF_BED_C_NAME) AS TYPE_OF_BED_C_NAME_filled,
    COUNT(RSN_FOR_BED_C_NAME) AS RSN_FOR_BED_C_NAME_filled,
    COUNT(DELIVERY_TYPE_C_NAME) AS DELIVERY_TYPE_C_NAME_filled,
    COUNT(LABOR_STATUS_C_NAME) AS LABOR_STATUS_C_NAME_filled,
    COUNT(ER_INJURY) AS ER_INJURY_filled,
    COUNT(ADT_ARRIVAL_TIME) AS ADT_ARRIVAL_TIME_filled,
    COUNT(ADT_ARRIVAL_STS_C_NAME) AS ADT_ARRIVAL_STS_C_NAME_filled,
    COUNT(HOSP_ADMSN_TIME) AS HOSP_ADMSN_TIME_filled,
    COUNT(ADMIT_CONF_STAT_C_NAME) AS ADMIT_CONF_STAT_C_NAME_filled,
    COUNT(HOSP_DISCH_TIME) AS HOSP_DISCH_TIME_filled,
    COUNT(HOSP_ADMSN_TYPE_C_NAME) AS HOSP_ADMSN_TYPE_C_NAME_filled,
    COUNT(ROOM_ID_ROOM_NAME) AS ROOM_ID_ROOM_NAME_filled,
    COUNT(HOSP_SERV_C_NAME) AS HOSP_SERV_C_NAME_filled,
    COUNT(MEANS_OF_DEPART_C_NAME) AS MEANS_OF_DEPART_C_NAME_filled,
    COUNT(DISCH_DISP_C_NAME) AS DISCH_DISP_C_NAME_filled,
    COUNT(DISCH_DEST_C_NAME) AS DISCH_DEST_C_NAME_filled,
    COUNT(TRANSFER_FROM_C_NAME) AS TRANSFER_FROM_C_NAME_filled,
    COUNT(MEANS_OF_ARRV_C_NAME) AS MEANS_OF_ARRV_C_NAME_filled,
    COUNT(ACUITY_LEVEL_C_NAME) AS ACUITY_LEVEL_C_NAME_filled,
    COUNT(HOSPIST_NEEDED_YN) AS HOSPIST_NEEDED_YN_filled,
    COUNT(ACCOMMODATION_C_NAME) AS ACCOMMODATION_C_NAME_filled,
    COUNT(ACCOM_REASON_C_NAME) AS ACCOM_REASON_C_NAME_filled,
    COUNT(INPATIENT_DATA_ID) AS INPATIENT_DATA_ID_filled,
    COUNT(PVT_HSP_ENC_C_NAME) AS PVT_HSP_ENC_C_NAME_filled,
    COUNT(ED_EPISODE_ID) AS ED_EPISODE_ID_filled,
    COUNT(ED_DISPOSITION_C_NAME) AS ED_DISPOSITION_C_NAME_filled,
    COUNT(ED_DISP_TIME) AS ED_DISP_TIME_filled,
    COUNT(FOLLOWUP_PROV_ID_PROV_NAME) AS FOLLOWUP_PROV_ID_PROV_NAME_filled,
    COUNT(PROV_CONT_INFO) AS PROV_CONT_INFO_filled,
    COUNT(OSHPD_ADMSN_SRC_C_NAME) AS OSHPD_ADMSN_SRC_C_NAME_filled,
    COUNT(OSHPD_LICENSURE_C_NAME) AS OSHPD_LICENSURE_C_NAME_filled,
    COUNT(OSHPD_ROUTE_C_NAME) AS OSHPD_ROUTE_C_NAME_filled,
    COUNT(INP_ADM_DATE) AS INP_ADM_DATE_filled,
    COUNT(COPY_TO_PCP_YN) AS COPY_TO_PCP_YN_filled,
    COUNT(ADOPTION_CASE_YN) AS ADOPTION_CASE_YN_filled,
    COUNT(PREOP_TEACHING_C_NAME) AS PREOP_TEACHING_C_NAME_filled,
    COUNT(PREOP_PRN_EVAL_C_NAME) AS PREOP_PRN_EVAL_C_NAME_filled,
    COUNT(PREOP_PH_SCREEN_C_NAME) AS PREOP_PH_SCREEN_C_NAME_filled,
    COUNT(LABOR_ACT_BIRTH_C_NAME) AS LABOR_ACT_BIRTH_C_NAME_filled,
    COUNT(LABOR_FEED_TYPE_C_NAME) AS LABOR_FEED_TYPE_C_NAME_filled,
    COUNT(PROC_SERV_C_NAME) AS PROC_SERV_C_NAME_filled,
    COUNT(ED_DEPARTURE_TIME) AS ED_DEPARTURE_TIME_filled,
    COUNT(TRIAGE_DATETIME) AS TRIAGE_DATETIME_filled,
    COUNT(TRIAGE_STATUS_C_NAME) AS TRIAGE_STATUS_C_NAME_filled,
    COUNT(INP_ADM_EVENT_ID) AS INP_ADM_EVENT_ID_filled,
    COUNT(INP_ADM_EVENT_DATE) AS INP_ADM_EVENT_DATE_filled,
    COUNT(INP_DWNGRD_EVNT_ID) AS INP_DWNGRD_EVNT_ID_filled,
    COUNT(INP_DWNGRD_DATE) AS INP_DWNGRD_DATE_filled,
    COUNT(INP_DWNGRD_EVNT_DT) AS INP_DWNGRD_EVNT_DT_filled,
    COUNT(OP_ADM_DATE) AS OP_ADM_DATE_filled,
    COUNT(EMER_ADM_DATE) AS EMER_ADM_DATE_filled,
    COUNT(OP_ADM_EVENT_ID) AS OP_ADM_EVENT_ID_filled,
    COUNT(EMER_ADM_EVENT_ID) AS EMER_ADM_EVENT_ID_filled,
    COUNT(PREREG_SOURCE_C_NAME) AS PREREG_SOURCE_C_NAME_filled,
    COUNT(HOV_CONF_STATUS_C_NAME) AS HOV_CONF_STATUS_C_NAME_filled,
    COUNT(RELIG_NEEDS_VISIT_C_NAME) AS RELIG_NEEDS_VISIT_C_NAME_filled,
    COUNT(DISCHARGE_CAT_C_NAME) AS DISCHARGE_CAT_C_NAME_filled,
    COUNT(EXP_DISCHARGE_TIME) AS EXP_DISCHARGE_TIME_filled,
    COUNT(BILL_ATTEND_PROV_ID_PROV_NAME) AS BILL_ATTEND_PROV_ID_PROV_NAME_filled,
    COUNT(OB_LD_LABORING_YN) AS OB_LD_LABORING_YN_filled,
    COUNT(OB_LD_LABOR_TM) AS OB_LD_LABOR_TM_filled,
    COUNT(TRIAGE_ID_TAG) AS TRIAGE_ID_TAG_filled,
    COUNT(TRIAGE_ID_TAG_CMT) AS TRIAGE_ID_TAG_CMT_filled,
    COUNT(TPLNT_BILL_STAT_C_NAME) AS TPLNT_BILL_STAT_C_NAME_filled,
    COUNT(ACTL_DELIVRY_METH_C_NAME) AS ACTL_DELIVRY_METH_C_NAME_filled,
    COUNT(PRENATAL_CARE_C_NAME) AS PRENATAL_CARE_C_NAME_filled,
    COUNT(AMBULANCE_CODE_C_NAME) AS AMBULANCE_CODE_C_NAME_filled,
    COUNT(MSE_DATE) AS MSE_DATE_filled,
    COUNT(ADMIT_PROV_TEXT) AS ADMIT_PROV_TEXT_filled,
    COUNT(ATTEND_PROV_TEXT) AS ATTEND_PROV_TEXT_filled,
    COUNT(PROV_PRIM_TEXT) AS PROV_PRIM_TEXT_filled,
    COUNT(PROV_PRIM_TEXT_PHON) AS PROV_PRIM_TEXT_PHON_filled,
    COUNT(HOSPITAL_AREA_ID_LOC_NAME) AS HOSPITAL_AREA_ID_LOC_NAME_filled,
    COUNT(CHIEF_COMPLAINT_C_NAME) AS CHIEF_COMPLAINT_C_NAME_filled,
    COUNT(NEED_FIN_CLR_YN) AS NEED_FIN_CLR_YN_filled
FROM PAT_ENC_HSP
GROUP BY YEAR(EXP_DISCHARGE_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_HSP_2
-- The PAT_ENC_HSP_2 table is the subsequent table for the PAT_ENC_HSP table, which is the primary table for hospital encounter information. Each record in this table is based on a patient contact serial
-- Bucket(s): Encounter / visit record
-- ==========================================================
SELECT
    YEAR(CONTACT_DATE) AS activity_year,
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(PAT_ENC_DATE_REAL) AS PAT_ENC_DATE_REAL_filled,
    COUNT(CONTACT_DATE) AS CONTACT_DATE_filled,
    COUNT(EX_DIS_DT_ENTR_DTTM) AS EX_DIS_DT_ENTR_DTTM_filled,
    COUNT(EX_DIS_TM_ENTR_DTTM) AS EX_DIS_TM_ENTR_DTTM_filled,
    COUNT(CONTRACT_REG_FLAG) AS CONTRACT_REG_FLAG_filled,
    COUNT(CONTRACT_CODE_C_NAME) AS CONTRACT_CODE_C_NAME_filled,
    COUNT(ACCEPTS_BLOOD_C_NAME) AS ACCEPTS_BLOOD_C_NAME_filled,
    COUNT(ED_ARRIVAL_DETAILS) AS ED_ARRIVAL_DETAILS_filled,
    COUNT(CONS_SEDATION_C_NAME) AS CONS_SEDATION_C_NAME_filled,
    COUNT(RESTRAINT_SECLUS_C_NAME) AS RESTRAINT_SECLUS_C_NAME_filled,
    COUNT(MULTI_PREG_YN) AS MULTI_PREG_YN_filled,
    COUNT(DISASTER_NUM) AS DISASTER_NUM_filled,
    COUNT(SRC_PATTERN_CSN_ID) AS SRC_PATTERN_CSN_ID_filled,
    COUNT(ENC_CLOSED_OR_COMPLETED_DATE) AS ENC_CLOSED_OR_COMPLETED_DATE_filled,
    COUNT(ED_DISPO_PAT_COND_C_NAME) AS ED_DISPO_PAT_COND_C_NAME_filled,
    COUNT(ADOPTION_TYPE_C_NAME) AS ADOPTION_TYPE_C_NAME_filled,
    COUNT(PRI_PROBLEM_ID) AS PRI_PROBLEM_ID_filled,
    COUNT(EXPECTED_DISCHRG_APPROX_TIME_C_NAME) AS EXPECTED_DISCHRG_APPROX_TIME_C_NAME_filled,
    COUNT(DISCH_MILEST_KICKOFF_UTC_DTTM) AS DISCH_MILEST_KICKOFF_UTC_DTTM_filled,
    COUNT(DISCH_MILEST_AUTO_MANAGED_YN) AS DISCH_MILEST_AUTO_MANAGED_YN_filled,
    COUNT(PREDICTED_LOS) AS PREDICTED_LOS_filled,
    COUNT(EXP_LOS_UPD_SRC_C_NAME) AS EXP_LOS_UPD_SRC_C_NAME_filled,
    COUNT(ED_ENC_SRC_C_NAME) AS ED_ENC_SRC_C_NAME_filled,
    COUNT(ED_DEPART_UTC_DTTM) AS ED_DEPART_UTC_DTTM_filled,
    COUNT(ADT_ARRIVAL_UTC_DTTM) AS ADT_ARRIVAL_UTC_DTTM_filled,
    COUNT(HOSP_DISCH_UTC_DTTM) AS HOSP_DISCH_UTC_DTTM_filled,
    COUNT(HOSP_ADMSN_UTC_DTTM) AS HOSP_ADMSN_UTC_DTTM_filled,
    COUNT(INP_ADMSN_UTC_DTTM) AS INP_ADMSN_UTC_DTTM_filled,
    COUNT(ED_HISTORICAL_YN) AS ED_HISTORICAL_YN_filled,
    COUNT(PATIENT_TASK_COMPLETION_RATE) AS PATIENT_TASK_COMPLETION_RATE_filled,
    COUNT(START_MED_REM_DISCHG_YN) AS START_MED_REM_DISCHG_YN_filled,
    COUNT(EXPECTED_DISCHARGE_UNKNOWN_YN) AS EXPECTED_DISCHARGE_UNKNOWN_YN_filled,
    COUNT(DUAL_ADMISSION_CSN) AS DUAL_ADMISSION_CSN_filled,
    COUNT(LOA_PAT_ENC_CSN_ID) AS LOA_PAT_ENC_CSN_ID_filled,
    COUNT(INITIAL_ADT_PAT_STAT_C_NAME) AS INITIAL_ADT_PAT_STAT_C_NAME_filled,
    COUNT(NOTIFICATION_SENT_FIRST_IP_YN) AS NOTIFICATION_SENT_FIRST_IP_YN_filled,
    COUNT(NOTIFICATION_SENT_OBS_ADMSN_YN) AS NOTIFICATION_SENT_OBS_ADMSN_YN_filled,
    COUNT(IB_ALERT_LENGTH_OF_STAY_MSG_ID) AS IB_ALERT_LENGTH_OF_STAY_MSG_ID_filled,
    COUNT(INITIAL_ADMIT_CONF_STAT_C_NAME) AS INITIAL_ADMIT_CONF_STAT_C_NAME_filled,
    COUNT(TRANSFER_COMMENTS) AS TRANSFER_COMMENTS_filled,
    COUNT(MED_READINESS_DTTM) AS MED_READINESS_DTTM_filled,
    COUNT(MED_READINESS_TIMEFRAM_C_NAME) AS MED_READINESS_TIMEFRAM_C_NAME_filled,
    COUNT(MED_READINESS_YN) AS MED_READINESS_YN_filled,
    COUNT(MED_READINESS_INST_ENTRY_DTTM) AS MED_READINESS_INST_ENTRY_DTTM_filled,
    COUNT(MED_READINESS_USER_ID) AS MED_READINESS_USER_ID_filled,
    COUNT(MED_READINESS_USER_ID_NAME) AS MED_READINESS_USER_ID_NAME_filled,
    COUNT(MED_READINESS_SOURCE_C_NAME) AS MED_READINESS_SOURCE_C_NAME_filled,
    COUNT(EXPECTED_DISCH_DISP_C_NAME) AS EXPECTED_DISCH_DISP_C_NAME_filled,
    COUNT(EXP_DISCH_DISP_USER_ID) AS EXP_DISCH_DISP_USER_ID_filled,
    COUNT(EXP_DISCH_DISP_USER_ID_NAME) AS EXP_DISCH_DISP_USER_ID_NAME_filled,
    COUNT(EXP_DISCH_DISP_ENTRY_UTC_DTTM) AS EXP_DISCH_DISP_ENTRY_UTC_DTTM_filled,
    COUNT(PRIMARY_LINKED_PAT_ENC_CSN_ID) AS PRIMARY_LINKED_PAT_ENC_CSN_ID_filled,
    COUNT(TODO_ADM_DISCLAIMER_ACTIVE_YN) AS TODO_ADM_DISCLAIMER_ACTIVE_YN_filled
FROM PAT_ENC_HSP_2
GROUP BY YEAR(CONTACT_DATE)
ORDER BY activity_year;

-- ==========================================================
-- Table: PAT_ENC_NO_SHOW
-- This table contains no-show documentation. When patients do not arrive for an appointment, they are marked as a no-show. Each no-show can have an associated action, outcome and comment. All of this do
-- Bucket(s): Appointment / scheduling status
-- ==========================================================
-- no date/datetime-typed column found on this table; flat total only
-- (no temporal-cutover read possible from this table alone)
SELECT
    COUNT(*) AS total_rows,
    COUNT(PAT_ENC_CSN_ID) AS PAT_ENC_CSN_ID_filled,
    COUNT(LINE) AS LINE_filled,
    COUNT(PAT_ID) AS PAT_ID_filled,
    COUNT(NO_SHOW_COMMENT) AS NO_SHOW_COMMENT_filled
FROM PAT_ENC_NO_SHOW;
